---
title: "Function"
author: "Taylor Ledford"
date: "9/27/2018"
output: html_document
---


```{r message=FALSE, warning=FALSE}
library(dplyr)
library(taRifx)
library(rattle)
rushing <- read.csv("2017_Rushing.csv")
combine <- read.csv("combine.csv")
Power5 <- read.csv("Powerof5.csv")
```

```{r}
names(rushing) <- c("Name", "Team", "Gms", "Att", "Yds", "Avg", "YPG", "Lg", "TD")
totalData <- merge(rushing, combine, by="Name", all=TRUE) %>%
  filter(Team != "NA" & College != "NA") %>%
  filter(POS != "ILB")
totalData$Yds <- as.numeric(destring(totalData$Yds))
totalData$Metric <- c(totalData$Yds/(totalData$Att/totalData$Gms))
totalData$Weight.lbs. <- unlist(totalData$Weight.lbs.)
totalData$College <- as.character(totalData$College)
Power5$School <- as.character(Power5$School)
```

```{r}
list <- vector("numeric", length=50)
CollegeCategory <- function(x) {
  for(i in 1:nrow(Power5)) {
    for(k in 1:nrow(totalData)) {
      if(Power5[i, "School"] == totalData[k, "College"]) {
        print(Power5[i, "School"])
        print(totalData[k, "College"])
        list[[k]] <- as.numeric("1")
        print(i)
        print(k)
      }
    }
  }
}
 
CollegeCategory("Category")
```
```{r}
df <- df %>%
  mutate(`Points Allowed` = `Points Allowed` * weightPA,
         `First Downs Allowed` = `First Downs Allowed` * weightFDA,
         `Points Scored` = `Points Scored` * weightPS,
         `Yards Per Play` = `Yards Per Play` * weightYPP,
         `Number of Punts` = `Number of Punts` * weightNP,
         `Takeaway Ratio` = `Takeaway Ratio` * weightTR)

df <- df %>%
  mutate(Metric = `Yards Per Play`
         + `Points Scored` 
         - `Points Allowed` 
         - `First Downs Allowed` 
         - `Number of Punts`
         + `Takeaway Ratio`)

df <- df %>%
  arrange(Year, -Metric)

Length80 <- df %>%
  filter(Year < 1995) %>%
  group_by(Year) %>%
  mutate(Rank = 1:28)

Length95 <- df %>%
  filter(Year > 1994 & Year < 1999) %>%
  group_by(Year) %>%
  mutate(Rank = 1:30)

Length96 <- df %>%
  filter(Year > 1998) %>%
  group_by(Year) %>%
  mutate(Rank = 1:31)

final2 <- rbind(Length80, Length95, Length96)

temp <- subset(final2, select=c("Year", "Team", "Rank"))
Superbowl2 <- rename(Superbowl2, "Team" = "Winners")
Superbowl2 <- merge(Superbowl2, temp, by=c("Year", "Team"))
Superbowl2 <- rename(Superbowl2, "Winners" = "Team")
Superbowl2 <- rename(Superbowl2, "WRank" = "Rank")

Superbowl2 <- rename(Superbowl2, "Team" = "Losers")
Superbowl2 <- merge(Superbowl2, temp, by=c("Year", "Team"))
Superbowl2 <- rename(Superbowl2, "Losers" = "Team")
Superbowl2 <- rename(Superbowl2, "LRank" = "Rank")

h <- Superbowl2$WRank - Superbowl2$LRank

h

mean(h < 0)
```
